### ISSUE TITLE
matplotlib RuntimeWarning: maximum number of figures opened.

### ISSUE THREAD

**Issue by joel-magnusson** [AlbinJS/IPTClock#2]
After spamming a bunch of buttons on the clock I get the following warning in the terminal:

> /Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/matplotlib/pyplot.py:524: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  max_open_warning, RuntimeWarning)

**Comment by AlbinJS** [comment]
This should now be adressed in the last commit, so I am closing this issue down.
