### ISSUE TITLE
Go to next/previous stage using keyboard

### ISSUE THREAD

**Issue by joel-magnusson** [AlbinJS/IPTClock#22]
See the title. In order to avoid accidentally changing the stage, this should require pressing at least two keys simultaneously.

**Comment by AlbinJS** [comment]
This has now been implemented.
Ctrl+Left : previous
Ctrl+Right : next

**Comment by joel-magnusson** [comment]
Ctrl+Left/Right is problematic on Mac. Can we try cmd+left/right instead (for mac only)?

**Comment by joel-magnusson** [comment]
Still needs to be fixed on Mac

**Comment by AlbinJS** [comment]
Should be fixed. Please confirm and then I will close the issue.

**Comment by joel-magnusson** [comment]
It works! However, perhaps we might want to add a toggle start/pause while we're at it. Mac could use cmd+enter.

**Comment by AlbinJS** [comment]
Fixed, closing the issue.
