### ISSUE TITLE
Text size

### ISSUE THREAD

**Issue by joel-magnusson** [AlbinJS/IPTClock#23]
The text size should be made to work well with standard projector resolution. The names of the participants are at the moment rather small.

**Comment by AlbinJS** [comment]
Text now scales with horisontal pixels and is manually changable through "Ctrl- +" "Ctrl- -".

**Comment by joel-magnusson** [comment]
Works, but it would be nice to also have a reset text size (to Default). This could be ctrl-0 or similar. Also, I think we might want to increase the relative size of the digital clock text.

**Comment by AlbinJS** [comment]
Implemented.
