### ISSUE TITLE
The clock is broken on Mac

### ISSUE THREAD

**Issue by joel-magnusson** [AlbinJS/IPTClock#24]
I get an immediate error message when running the clock as of https://github.com/AlbinJS/IPTClock/commit/9ab63129e770414bd2c5eaf673d075eb2bc8435d

`/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/matplotlib/__init__.py:1357: UserWarning:  This call to matplotlib.use() has no effect
because the backend has already been chosen;
matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

  warnings.warn(_use_error_msg)
2017-03-01 22:45:25.313 Python[22239:1792250] -[NSApplication _setup:]: unrecognized selector sent to instance 0x101237df0
2017-03-01 22:45:25.316 Python[22239:1792250] An uncaught exception was raised
2017-03-01 22:45:25.316 Python[22239:1792250] -[NSApplication _setup:]: unrecognized selector sent to instance 0x101237df0
2017-03-01 22:45:25.316 Python[22239:1792250] (
        0   CoreFoundation                      0x00007fff850c003c __exceptionPreprocess + 172
        1   libobjc.A.dylib                     0x00007fff8b35876e objc_exception_throw + 43
        2   CoreFoundation                      0x00007fff850c30ad -[NSObject(NSObject) doesNotRecognizeSelector:] + 205
        3   CoreFoundation                      0x00007fff85008e24 ___forwarding___ + 1028
        4   CoreFoundation                      0x00007fff85008998 _CF_forwarding_prep_0 + 120
        5   Tk                                  0x00000001014e0527 TkpInit + 476
        6   Tk                                  0x000000010145aaca Tk_Init + 1788
        7   _tkinter.cpython-35m-darwin.so      0x00000001003f0dcd Tcl_AppInit + 77
        8   _tkinter.cpython-35m-darwin.so      0x00000001003ee7d9 _tkinter_create + 889
        9   Python                              0x0000000100065479 PyCFunction_Call + 233
        10  Python                              0x00000001000f1631 PyEval_EvalFrameEx + 36305
        11  Python                              0x00000001000f2510 _PyEval_EvalCodeWithName + 2368
        12  Python                              0x00000001000f2617 PyEval_EvalCodeEx + 71
        13  Python                              0x000000010004031a function_call + 186
        14  Python                              0x000000010000d713 PyObject_Call + 99
        15  Python                              0x00000001000286fc method_call + 140
        16  Python                              0x000000010000d713 PyObject_Call + 99
        17  Python                              0x0000000100082a01 slot_tp_init + 81
        18  Python                              0x0000000100079624 type_call + 212
        19  Python                              0x000000010000d713 PyObject_Call + 99
        20  Python                              0x00000001000ec852 PyEval_EvalFrameEx + 16370
        21  Python                              0x00000001000f2510 _PyEval_EvalCodeWithName + 2368
        22  Python                              0x00000001000f2671 PyEval_EvalCode + 81
        23  Python                              0x000000010012083e PyRun_FileExFlags + 206
        24  Python                              0x0000000100120adf PyRun_SimpleFileExFlags + 447
        25  Python                              0x0000000100139858 Py_Main + 3512
        26  Python                              0x0000000100000e32 Python + 3634
        27  Python                              0x0000000100000c84 Python + 3204
        28  ???                                 0x0000000000000002 0x0 + 2
)
2017-03-01 22:45:25.318 Python[22239:1792250] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSApplication _setup:]: unrecognized selector sent to instance 0x101237df0'
*** First throw call stack:
(
        0   CoreFoundation                      0x00007fff850c003c __exceptionPreprocess + 172
        1   libobjc.A.dylib                     0x00007fff8b35876e objc_exception_throw + 43
        2   CoreFoundation                      0x00007fff850c30ad -[NSObject(NSObject) doesNotRecognizeSelector:] + 205
        3   CoreFoundation                      0x00007fff85008e24 ___forwarding___ + 1028
        4   CoreFoundation                      0x00007fff85008998 _CF_forwarding_prep_0 + 120
        5   Tk                                  0x00000001014e0527 TkpInit + 476
        6   Tk                                  0x000000010145aaca Tk_Init + 1788
        7   _tkinter.cpython-35m-darwin.so      0x00000001003f0dcd Tcl_AppInit + 77
        8   _tkinter.cpython-35m-darwin.so      0x00000001003ee7d9 _tkinter_create + 889
        9   Python                              0x0000000100065479 PyCFunction_Call + 233
        10  Python                              0x00000001000f1631 PyEval_EvalFrameEx + 36305
        11  Python                              0x00000001000f2510 _PyEval_EvalCodeWithName + 2368
        12  Python                              0x00000001000f2617 PyEval_EvalCodeEx + 71
        13  Python                              0x000000010004031a function_call + 186
        14  Python                              0x000000010000d713 PyObject_Call + 99
        15  Python                              0x00000001000286fc method_call + 140
        16  Python                              0x000000010000d713 PyObject_Call + 99
        17  Python                              0x0000000100082a01 slot_tp_init + 81
        18  Python                              0x0000000100079624 type_call + 212
        19  Python                              0x000000010000d713 PyObject_Call + 99
        20  Python                              0x00000001000ec852 PyEval_EvalFrameEx + 16370
        21  Python                              0x00000001000f2510 _PyEval_EvalCodeWithName + 2368
        22  Python                              0x00000001000f2671 PyEval_EvalCode + 81
        23  Python                              0x000000010012083e PyRun_FileExFlags + 206
        24  Python                              0x0000000100120adf PyRun_SimpleFileExFlags + 447
        25  Python                              0x0000000100139858 Py_Main + 3512
        26  Python                              0x0000000100000e32 Python + 3634
        27  Python                              0x0000000100000c84 Python + 3204
        28  ???                                 0x0000000000000002 0x0 + 2
)
libc++abi.dylib: terminating with uncaught exception of type NSException
Abort trap: 6
`

**Comment by AlbinJS** [comment]
This is issue should now be fixed as of commit  c071df1. I'm closing it down.
