### ISSUE TITLE
AttributeError: 'AxesSubplot' object has no attribute 'set_facecolor'

### ISSUE THREAD

**Issue by joel-magnusson** [AlbinJS/IPTClock#25]
I get the following error as of https://github.com/AlbinJS/IPTClock/commit/ccc3568bc078f72dbb5422eeb8c960e99619fa72:
`File "/Users/joel/Coding/IPTClock/Classes/iptclock_classes.py", line 155, in create_clock_canvas
ax.set_facecolor(None)
AttributeError: 'AxesSubplot' object has no attribute 'set_facecolor'`

It runs if I comment out the relevant line, but I'm unsure of what the graphical difference is.

**Comment by AlbinJS** [comment]
Hmmm, it also works for me when commented out... 
When I wrote it it was probably clever...
I have commented it out for now...
