### ISSUE TITLE
Graphical changes

### ISSUE THREAD

**Issue by joel-magnusson** [AlbinJS/IPTClock#27]
Currently the default background in the logos area makes it look ugly. I think we should simply enforce a white background, because that is what we will want to see on the projector in the end anyway.

Furthermore, the clock is currently way too small...

And the "About page" could use some fixes.

Lastly. Ask Joakim to chip in with new logos!

![image](https://cloud.githubusercontent.com/assets/11462718/23801147/5cead892-05af-11e7-9692-9fa8f16c2f0a.png)

**Comment by AlbinJS** [comment]
Fixed colours and about, colours are now enforced. Clock sizing isn't done yet.

**Comment by AlbinJS** [comment]
I can't really duplicate your sizing problem with the graphical clock. Do you still experience this problem?

**Comment by joel-magnusson** [comment]
The sizing problem with the graphical clock seems to have been fixed now. However, the enforcing of colors does not seem to have worked on Mac. The relevant areas were however colored red in https://github.com/AlbinJS/IPTClock/commit/b158ae062b29d3fe8e41963fb84ce9e47741b746.

![image](https://cloud.githubusercontent.com/assets/11462718/23938795/1a0b29b6-095e-11e7-94d3-accfe4ab3cb4.png)


![image](https://cloud.githubusercontent.com/assets/11462718/23938676/8fd17872-095d-11e7-9afc-102225efafcd.png)

**Comment by joel-magnusson** [comment]
Scratch that last comment. I just changed the background color from None to "white" in the configs and it now checks out. Closing this issue.
