### ISSUE TITLE
Create a standalone config window

### ISSUE THREAD

**Issue by vbonvin** [AlbinJS/IPTClock#29]
A nice improvement to the existing setup would be to have a standalone window from which you can control the main display. That way, the clock can be displayed fullscreen on the second monitor and the chairman can change the stages from his laptop screen as well as doing other stuff without interfering with the main display.

**Comment by AlbinJS** [comment]
I see what you mean but I don't agree. I think it is easy enough to change the clock either by mouse or by short-cuts. If for some reason you'd want to do other stuff while the clock runs, you could just run with extended desktop instead of cloned and solve it that way.

**Comment by AlbinJS** [comment]
This is somewhat incorporated into the new configuration window under the "Edit" menu. The buttons still remain on the main window, but the edit buttons has been removed. I'm closing this issue.
