### ISSUE TITLE
Closing the clock by closing its window environment produces error/warning messages

### ISSUE THREAD

**Issue by joel-magnusson** [AlbinJS/IPTClock#3]
Closing the clock by closing the window environment produces an error/warning in the terminal. Also, the number printed in the message is varying.

Message:
> invalid command name "4458719624update_countdown"
    while executing
"4458719624update_countdown"
    ("after" script)

**Comment by AlbinJS** [comment]
Fixed using protocol handlers with. Will be present in the next commit.
