### ISSUE TITLE
Add a Set Time button

### ISSUE THREAD

**Issue by vbonvin** [AlbinJS/IPTClock#32]
If for some reason the clock crashes and need to be restarted, or the chairman misclick and start a new stage too early, it would be convenient to have the option to manually set the clock at a given time before starting it.

**Comment by AlbinJS** [comment]
Excellent proposition. I implemented it in the latest commit. You can bring up a pop-up for changing it either by <Ctrl + u > or simply by left clicking on the count down (the numbers on top). I also implemented a feature to alter the present time in increments of 5s by using Ctrl + n/m. For Mac substitute Ctrl for Command. I appreciate any feedback.
