### ISSUE TITLE
Allow the user to chose between countdown and clock

### ISSUE THREAD

**Issue by vbonvin** [AlbinJS/IPTClock#33]
The current displays is a bit misleading, where the time displayed is the remaining time and the clock displays the elapsed time. It would be nice to: 

  * Make the two of them consistent (i.e. both elapsed time or remaining time)
  * Allow the user to chose between one mode or the other (with a button ? )  and add a small note somewhere on the display which mode is currently active.

That would also be helpful for  #32

**Comment by AlbinJS** [comment]
This is a design choice and, although I can see the appeal of being able to change modes, I think that the clock should be written to maintain continuity over the different fights.

**Comment by vbonvin** [comment]
I agree with the consistency arguments between the fights. I'm still slightly bothered by the countdown-mode timer + clock-mode display, but that's a really minor thing. Since you prefer it like it is, let's close the issue.
