### ISSUE TITLE
The clock switches back to the yellow, from red, after every full lap

### ISSUE THREAD

**Issue by joel-magnusson** [AlbinJS/IPTClock#6]
We could do it in two ways:

Allow a list of colors (larger than the current) that the clock is supposed to cycle through and/or end with a color switcher (such that the background switches to the previous color of the wedge and vice versa).

**Comment by AlbinJS** [comment]
Indeed, although I doubt this will be a problem outside from the startup setting, since the countdown will  be in the range of minutes in the stages. But the startup settingt can also be changed to 99:59,

**Comment by joel-magnusson** [comment]
It has happened that the clock has ticked for > 2 laps on some of the ~2 minute stages (people failing miserably with technology). If we only implement a better switch (e.g. yellow -> red -> yellow -> red) then the entire clock will not make a strange colour transition at 12 o'clock on laps >= 2.

It's a small aesthetic thing :P

**Comment by AlbinJS** [comment]
Problem fixed, closing issue.
